# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-21 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('amt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('phno', models.PositiveIntegerField()),
                ('institute', models.CharField(max_length=70)),
                ('regid', models.CharField(max_length=10)),
                ('toPay', models.IntegerField()),
                ('PaidAmt', models.IntegerField()),
                ('events', models.ManyToManyField(to='website.Event')),
                ('lastEdit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Admin')),
            ],
        ),
    ]
